# Generated by Django 3.2.15 on 2022-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20220921_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='moves',
            field=models.CharField(max_length=500),
        ),
    ]
