# Generated by Django 3.2.15 on 2022-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_pokemon_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='moves',
            field=models.IntegerField(),
        ),
    ]
