# Generated by Django 3.2.15 on 2022-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_pokemon_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='official_artwork',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
