# Generated by Django 3.2.15 on 2022-09-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20220921_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='updated_timestamp',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
