# Generated by Django 3.2.15 on 2022-09-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_alter_pokemon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='created_timestamp',
        ),
    ]
